= Build Frameworks Group
:keywords: build, c++, library
:copyright: Copyright 2017-2018 Rene Rivera
:reproducible:
:source-highlighter: highlightjs
:source-language: c++
:toc: left
:toc-title: Build Frameworks Group
:sectanchors:
:docinfo: shared
:docinfo-dir: ../bin/asciidoctor-backend-html5
:nofooter:

We are a group of developers writing software solutions to solve common
software building problems. Our goal is to provide a highly reused set
of components that advances software building technology.

== Projects

=== `std_cpp`

This is library proposes to standardize the build interface for compiling
C++ source. This is both a specification and an implementation proof. As
such it provides both a library that can be used to build upon and a
minimal `std_cpp` tool for some common C++ compilers.

* Source and proposal in https://github.com/bfgroup/std_cpp[GitHub project].

=== `conan-b2gen`

This Conan package is a full feature generator for the `B2` build system.
It's a multi-generator that respects the multi-variant nature of `B2` while
making it easy to use Conan.

* Documentation and usage is at the
  https://github.com/bfgroup/conan-b2gen[GitHub project].
* You can install it directly by using the
  https://bintray.com/bfgroup/public-conan[bfgroup Bintray Conan repository].

=== `jam_pygments`

A Jam/B2 build description language lexer for Pygments. This allows syntax
coloring of Jam/B2 source code for any tool that uses the Pygments module.
Which includes Asciidoctor with the appropriate extension.

* You can find documentation and usage at the
  https://github.com/bfgroup/jam_pygments[GitHub project].
