= Build Frameworks Group
:keywords: build, c++, library
:copyright: Copyright 2017-2021 René Ferdinand Rivera Morell
:reproducible:
:stylesheet: amber.css
:toc: left
:toc-title: Build Frameworks Group
:sectanchors:
:docinfo: shared
:docinfo-dir: ../bin/asciidoctor-backend-html5
:nofooter:
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:CPP: C++


We are a group of developers writing software solutions to solve common
software building problems. Our goal is to provide a highly reused set
of components that advances software building technology.

== B2

B2 makes it easy to build C++ projects, everywhere. B2 has been the primary
build system for the link:https://boost.org/[Boost C++ Libraries] for many
years. The main development now lives here at BFG in order to grow the
audience outside of Boost.

* Visit the B2 link:./b2/[section] for additional information, documentation
  and downloads.

== Duck Invoke

A simple to use, single header, `tag_invoke` utility for C++11.

* Check out the link:https://github.com/bfgroup/duck_invoke[repository] or
  link:./duck_invoke/[documentation] for more
  information.

== Lyra

A simple to use, composing, command line parser for C++ 11 and beyond.
The header only library makes creating and using common cases of command lines
easy and natural.

* Check out the link:./Lyra/[web-site] for more
  information.

== CI Playground

In a single repository we collect, and experiment, with building a C++
program in a variety of Cloud Continuous Integration *free* providers.
We hope to make it easier to get people using the large number of free
build and testing resources available to Open Source Software authors.

* For periodic releases and the living demonstration see the repo at
  the https://github.com/bfgroup/ci_playground[GitHub project].

== {CPP} Tooling Statistics

Here we collect and present a variety of performance metrics for {CPP} tools.
The goal is to illuminate the current state of the {CPP} tooling ecosystem to
inform future directions for improvements.

* Read about the statistics in the link:./cpp_tooling_stats/[web-site].

== std_cpp

This is library proposes to standardize the build interface for compiling
{CPP} source. This is both a specification and an implementation proof. As
such it provides both a library that can be used to build upon and a
minimal `std_cpp` tool for some common {CPP} compilers.

* Source and proposal in https://github.com/bfgroup/std_cpp[GitHub project].

== jam_pygments

A Jam/B2 build description language lexer for Pygments. This allows syntax
coloring of Jam/B2 source code for any tool that uses the Pygments module.
Which includes Asciidoctor with the appropriate extension.

* You can find documentation and usage at the
  https://github.com/bfgroup/jam_pygments[GitHub project].

== conan-b2gen

NOTE: This project is now dormant as it was merged into the Conan mainline
release. It's here for historical reference.

This Conan package is a full feature generator for the `B2` build system.
It's a multi-generator that respects the multi-variant nature of `B2` while
making it easy to use Conan.

* Documentation and usage is at the
  https://github.com/bfgroup/conan-b2gen[GitHub project].
